apiVersion: v1  # API version being used
kind: PersistentVolumeClaim  # Kind of object being created
metadata:
  name: mongo-pvc  # Name of PersistentVolumeClaim
spec:
  accessModes:
    - ReadWriteMany  # Access mode of volume -> multiple nodes to read/write
  resources:
    requests:
      storage: 1Gi  # Amount of storage
  storageClassName: "demo-storage"  # Name of the StorageClass