apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: australia-southeast2-docker.pkg.dev/sit323-24t1-te-claire-15b5962/app-registry/backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_CONNECTION_STRING
          value: mongodb://mongo:27017/DataBuildApp