# Google Cloud deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: australia-southeast2-docker.pkg.dev/sit323-24t1-te-claire-15b5962/app-registry/backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo-service:27017/DataBuildApp"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"    
          limits:
            memory: "512Mi" 
            cpu: "1000m"   



# Docker Desktop deployment
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#       - name: backend
#         image: your-backend-image
#         ports:
#         - containerPort: 3000
#         env:
#         - name: MONGODB_URI
#           value: "mongodb://mongo-service:27017/DataBuildApp"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
# spec:
#   selector:
#     app: backend
#   ports:
#     - protocol: TCP
#       port: 3000
#       targetPort: 3000
