version: '3.8'

services:
  mongo:
    image: mongo:4.2.0
    container_name: project-mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo

  backend:
    build:
      context: ./backend
    image: backend-image:latest
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    environment:
      - MONGODB_URI=mongodb://mongo:27017/DataBuildApp

  frontend:
    build:
      context: ./frontend
    image: frontend-image:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - react-express

networks:
  express-mongo:
  react-express:

volumes:
  mongo_data:
