version: '3.8'

services:
  project-mongo:
    image: mongo:4.2.0
    container_name: project-mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo

  backend:
    build:
      context: ./backend
    image: australia-southeast2-docker.pkg.dev/sit323-24t1-te-claire-15b5962/app-registry/backend:latest
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - project-mongo
    networks:
      - express-mongo
      - react-express
    environment:
      - MONGO_CONNECTION_STRING=mongodb://project-mongo:27017/DataBuildApp

  frontend:
    build:
      context: ./frontend
    image: australia-southeast2-docker.pkg.dev/sit323-24t1-te-claire-15b5962/app-registry/frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - react-express

networks:
  express-mongo:
  react-express:

volumes:
  mongo_data:
