# # Pull the Node image from Docker Hub
# FROM node:14-slim

# # Setting Working Directory
# WORKDIR /usr/app

# # Copying only package.json
# COPY package*.json ./

# # Install Dependencies
# RUN npm install

# # Copy rest of the code to container
# COPY . .

# EXPOSE 3000

# # Run the React app
# CMD ["npm", "start"]

# # Pull the Node image from Docker Hub
# FROM node:16-slim

# # Setting Working Directory
# WORKDIR /usr/app

# # Copying only package.json
# COPY frontend/package*.json ./

# # Install Dependencies
# RUN npm install

# # Copy rest of the code to container
# COPY frontend/ .

# EXPOSE 3000

# # Run the React app in development mode
# CMD ["npm", "start"]

# Use the official nginx image as the base image
FROM nginx:alpine

# Copy the build output to replace the default nginx contents
COPY build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Command to run nginx
CMD ["nginx", "-g", "daemon off;"]


