# # Pull the Node image from Docker Hub
# FROM node:14-slim

# # Setting Working Directory
# WORKDIR /usr/app

# # Copying only package.json
# COPY package*.json ./

# # Install Dependencies
# RUN npm install

# # Copy rest of the code to container
# COPY . .

# EXPOSE 3000

# # Run the React app
# CMD ["npm", "start"]

# Pull the Node image from Docker Hub
FROM node:16-slim

# Setting Working Directory
WORKDIR /usr/app

# Copying package.json and package-lock.json
COPY package*.json ./

# Install Dependencies
RUN npm install

# Copy rest of the code to container
COPY . .

EXPOSE 80

# Run the React app in development mode
CMD ["npm", "start"]

