# # Pull the Node image from Docker Hub
# FROM node:14-slim

# # Setting Working Directory
# WORKDIR /usr/app

# # Copying only package.json
# COPY package*.json ./

# # Install Dependencies
# RUN npm install

# # Copy rest of the code to container
# COPY . .

# EXPOSE 3080

# # Run the API on Nodemon
# CMD ["npm", "run", "dev"]


# Pull the Node image from Docker Hub
FROM node:16-slim

# Setting Working Directory
WORKDIR /usr/app

# Copying only package.json
COPY backend/package*.json ./

# Install Dependencies
RUN npm install

# Copy rest of the code to container
COPY backend/ .

EXPOSE 3000

# Run the API on Nodemon in development mode
CMD ["npm", "run", "dev"]
