# Pull the Node image from Docker Hub
FROM node:16-slim

# Setting Working Directory
WORKDIR /usr/app

# Copying only package.json
COPY package*.json ./

# Install Dependencies
RUN npm install

# Copy rest of the code to container
COPY . .

# Ensure the public directory is copied
COPY public /usr/app/public

EXPOSE 3080

# Run the API on Nodemon
CMD ["npm", "run", "dev"]