# # Pull the Node image from Docker Hub
# FROM node:14-slim

# # Setting Working Directory
# WORKDIR /usr/app

# # Copying only package.json
# COPY package*.json ./

# # Install Dependencies
# RUN npm install

# # Copy rest of the code to container
# COPY . .

# EXPOSE 3080

# # Run the API on Nodemon
# CMD ["npm", "run", "dev"]

# Pull the Node image from Docker Hub
FROM node:16-slim

# Setting Working Directory
WORKDIR /usr/app

# Copying only package.json
COPY package*.json ./

# Install Dependencies
RUN npm install

# Copy rest of the code to container
COPY . .

# Copy frontend build to public directory
COPY ../frontend/build /usr/app/public

# Expose port 3000
EXPOSE 3000

# Run the API on Nodemon
CMD ["npm", "run", "dev"]
