version: "3"
services:
  
  frontend:
   build:
      context: ./frontend
      dockerfile: Dockerfile.dev
   ports:
    -  3000:3000
   container_name: data-build-frontend
   networks:
    -  data-build-net
   volumes:
    -  ./frontend/src:/usr/app/src
    -  ./frontend/public:/usr/app/public
   depends_on:
    - backend
   stdin_open: true
   tty: true

  backend:
   build:
      context: ./backend
      dockerfile: Dockerfile.dev
   ports:
     - 3080:3080
   container_name: data-build-backend
   networks:
     - data-build-net
   volumes:
    - ./backend/src:/usr/app/src
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - data-build-net
    volumes:
      - mongo-data:/data/db

networks:
  data-build-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
